### ISSUE TITLE
Move the setup index logic out of the Store

### ISSUE THREAD

**Issue by tstojecki** [tstojecki/elastic-identity#2]
Looking at the other providers (Entity Framework, Mongo) they do not handle DB setup logic inside of the store. I would like to move SetupIndex as well as I don't believe the store is the right place to do that. We can expose a different class in the project to help with that.

**Comment by Ry-K** [comment]
I agree. In fact, I don't think the index should be handled at all as a) you can create an index on-the-fly simply by sending data to it b) analyzer setup isn't useful as user fields are not_analyzed (or should be) and the goal isn't full text search against the data in the identity store anyway.

This leads into my curiosity with [this line](https://github.com/tstojecki/elastic-identity/blob/dev/src/ElasticIdentity/ElasticUser.cs#L79). I disagree that we should lowercase the username (analyze it) in how it is stored and searched for; I expect my username to be case-sensitive.

**Comment by tstojecki** [comment]
Thanks for the feedback, glad to hear you agree on moving the setup logic out.

Regarding the lowercase match on the username, I may have missed your point, but I think most of the time the username is case insensitive. If we take the lowercase analyzer out and .ToLower, we would make the findbyusername case sensitive, would we not? I can't think of a login form that requires that.

**Comment by Ry-K** [comment]
I agree on username's generally case-insensitive. I wasn't being clear and left out an portion. ElasticUser.UserName is analyzed. I need to check out how things work when you specify an analyzer (whether it applies on both GET and PUT) but (I'm not suggesting use it) the out-of-the-box analyzer lowercases strings when indexing and also when you search - so lowercasing the UserName [here](https://github.com/tstojecki/elastic-identity/blob/dev/src/ElasticIdentity/ElasticUser.cs#L79)isn't really necessary.

Another thought, and maybe you've seen this also, is that a lot of uses I've seen personally and in the field with Elasticsearch manage string data with two fields (multi-field mapping). So the the actual field name, say FieldA, is analyzed and a sub-field (usually .raw), FieldA.raw, would contain the raw text as-is with no analysis. Lower-casing UserName in code prevents that from being done, if desired, by a simple PUT mapping template.

**Comment by tstojecki** [comment]
I see. If you have cycles to test this out let me know of the outcome. I am all for removing it if we don't need it.

**Comment by Ry-K** [comment]
It's possible that this will be figured out as part of this issue. I see nothing wrong with the way things are now. I'm doing some thinking on this one though.

**Comment by Ry-K** [comment]
Before I go further, I would like to ensure I am clear on how things work here (sorry, I'm familiar with BitBucket/Atlassian more). I committed just a bit ago, not thinking I wasn't on a branch that is specifically related to the issue. Is that how you would like to operate, or is there a similar way I am just not aware of with GitHub?

**Comment by tstojecki** [comment]
I think it is fine if we develop small fixes and enhancements against the dev branch. Please make sure the dev branch is synced up with master. Master should always reflect the current release.

For larger pieces of work, let's create a feature specific branch. An example could be the work you did on IUserLockoutStore. For something like that, I suggest we go with a separate branch.

**Comment by tstojecki** [comment]
https://github.com/tstojecki/elastic-identity/commit/c694095805b5f24bba353d924d87c138a6ea4ddb
