### ISSUE TITLE
Remove Wrap() 

### ISSUE THREAD

**Issue by tstojecki** [tstojecki/elastic-identity#3]
ElasticClient supports logging of each request/response through ConnectionSettings.SetConnectionStatusHandle and the new ctor allows the fully configured ElasticClient to be passed through. With that, I don't see as much of a need to fire an event prior to every Nest call. IMO that would clean up the code quite a bit.

**Comment by Ry-K** [comment]
Can you provide some information on that setting? I wasn't able to find it, but I am semi-familiar with [this](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs#L134).

**Comment by tstojecki** [comment]
https://github.com/tstojecki/elastic-identity/commit/fe851a803971c5c1bdb00b38a0a0817bf7f80f51
