### ISSUE TITLE
Implement IUserLockoutStore

### ISSUE THREAD

**Issue by Ry-K** [tstojecki/elastic-identity#5]
In use with an ASP.NET MVC4 application, the library works as intended although after registering a new user and logging off, attempting to login again with the same user results in:

Server Error in '/' Application.

Store does not implement IUserLockoutStore<TUser>.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NotSupportedException: Store does not implement IUserLockoutStore<TUser>.

**Comment by Ry-K** [comment]
I have the changes ready for this also.

**Comment by tstojecki** [comment]
Yes, we actually ran into that issue in asp.net mvc 5. I believe this is the issue
http://stackoverflow.com/questions/30957060/store-does-not-implement-iuserlockoutstoretuser

Long story short, the 'optional' interfaces are not really optional.

If you have the code ready, please send a PR.

**Comment by Ry-K** [comment]
Yes, I believe you are correct. With mvc5, the VS template provided, did you run across the need for a method with this signature somewhere? It just calls manager.CreateIdentityAsync(). Wasn't clear how that should be handled; it was in the ApplicationUser class (IIRC).

`public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ElasticUser> manager)`

**Comment by tstojecki** [comment]
Merged as part of #6 

GenerateUserIdentityAsync is used for security stamp validation. You should see it in the setup of the cookie middleware with .UseCookieAuthentication. This will kick in if you change user's password while you're logged in.
